// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: wallmasterr (https://sketchfab.com/wallmasterr)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
// Title: Tenhun Falling spaceman (FanArt)
// */

// import React, { useEffect, useRef } from "react";
// import { useGLTF, useAnimations } from "@react-three/drei";
// import { useMotionValue, useSpring } from "motion/react";
// import { useFrame } from "@react-three/fiber";

// export function Astronaut(props) {
//   const group = useRef();
//   const { nodes, materials, animations } = useGLTF(
//     "/models/tenhun_falling_spaceman_fanart.glb"
//   );
//   const { actions } = useAnimations(animations, group);
//   useEffect(() => {
//     if (animations.length > 0) {
//       actions[animations[0].name]?.play();
//     }
//   }, [actions, animations]);

//   const yPosition = useMotionValue(5);
//   const ySpring = useSpring(yPosition, { damping: 30 });
//   useEffect(() => {
//     ySpring.set(-1);
//   }, [ySpring]);
//   useFrame(() => {
//     group.current.position.y = ySpring.get();
//   });
//   return (
//     <group
//       ref={group}
//       {...props}
//       dispose={null}
//       rotation={[-Math.PI / 2, -0.2, 2.2]}
//       scale={props.scale || 0.3}
//       position={props.position || [1.3, -1, 0]}
//     >
//       <group name="Sketchfab_Scene">
//         <group name="Sketchfab_model">
//           <group name="Root">
//             <group name="metarig">
//               <primitive object={nodes.metarig_rootJoint} />
//               <skinnedMesh
//                 name="Cube001_0"
//                 geometry={nodes.Cube001_0.geometry}
//                 material={materials["AstronautFallingTexture.png"]}
//                 skeleton={nodes.Cube001_0.skeleton}
//               />
//               <skinnedMesh
//                 name="Cube005_0"
//                 geometry={nodes.Cube005_0.geometry}
//                 material={materials["AstronautFallingTexture.png"]}
//                 skeleton={nodes.Cube005_0.skeleton}
//               />
//               <skinnedMesh
//                 name="Cube002_0"
//                 geometry={nodes.Cube002_0.geometry}
//                 material={materials["AstronautFallingTexture.png"]}
//                 skeleton={nodes.Cube002_0.skeleton}
//               />
//               <skinnedMesh
//                 name="Plane_0"
//                 geometry={nodes.Plane_0.geometry}
//                 material={materials["AstronautFallingTexture.png"]}
//                 skeleton={nodes.Plane_0.skeleton}
//               />
//               <skinnedMesh
//                 name="Cube008_0"
//                 geometry={nodes.Cube008_0.geometry}
//                 material={materials["AstronautFallingTexture.png"]}
//                 skeleton={nodes.Cube008_0.skeleton}
//               />
//               <skinnedMesh
//                 name="Cube004_0"
//                 geometry={nodes.Cube004_0.geometry}
//                 material={materials["AstronautFallingTexture.png"]}
//                 skeleton={nodes.Cube004_0.skeleton}
//               />
//               <skinnedMesh
//                 name="Cube003_0"
//                 geometry={nodes.Cube003_0.geometry}
//                 material={materials["AstronautFallingTexture.png"]}
//                 skeleton={nodes.Cube003_0.skeleton}
//               />
//               <skinnedMesh
//                 name="Cube_0"
//                 geometry={nodes.Cube_0.geometry}
//                 material={materials["AstronautFallingTexture.png"]}
//                 skeleton={nodes.Cube_0.skeleton}
//               />
//               <skinnedMesh
//                 name="Cube009_0"
//                 geometry={nodes.Cube009_0.geometry}
//                 material={materials["AstronautFallingTexture.png"]}
//                 skeleton={nodes.Cube009_0.skeleton}
//               />
//               <skinnedMesh
//                 name="Cube011_0"
//                 geometry={nodes.Cube011_0.geometry}
//                 material={materials["AstronautFallingTexture.png"]}
//                 skeleton={nodes.Cube011_0.skeleton}
//               />
//               <group name="Cube001" />
//               <group name="Cube005" />
//               <group name="Cube002" />
//               <group name="Plane" />
//               <group name="Cube008" />
//               <group name="Cube004" />
//               <group name="Cube003" />
//               <group name="Cube" />
//               <group
//                 name="Cube009"
//                 rotation={[-2.708, 0.013, -1.447]}
//                 scale={1.307}
//               />
//               <group name="Cube011" />
//             </group>
//           </group>
//         </group>
//       </group>
//     </group>
//   );
// }

// useGLTF.preload("/models/tenhun_falling_spaceman_fanart.glb");


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Speedy BOY (https://sketchfab.com/speedy2311playz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/anime-vfx-1b10dafa65bd4290985d4602b82c55e1
Title: ANIME VFX
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Planet(props) {
//   const { nodes, materials } = useGLTF('/models/anime_vfx.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_4.geometry}
//         material={materials['Material.009']}
//         position={[0, 1.5, 0]}
//         rotation={[0.3, -0.7, 0.6]}
//         scale={1.2}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_6.geometry}
//         material={materials['Material.007']}
//         position={[0, 1.5, 0]}
//         rotation={[0, 0, -0.1]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_8.geometry}
//         material={materials['Material.008']}
//         position={[-0.1, 1.5, 0]}
//         rotation={[-3, 0.8, 2.5]}
//         scale={1.1}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_10.geometry}
//         material={materials['Material.008']}
//         position={[0, 1.8, -0.1]}
//         rotation={[2.4, 0.4, 0.1]}
//         scale={[2.4, 4.5, 2.4]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_12.geometry}
//         material={materials['Material.007']}
//         position={[-0.1, 1.6, 0]}
//         scale={[2, 3.8, 2]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_14.geometry}
//         material={materials['Material.008']}
//         position={[-0.1, 0.6, 0]}
//         scale={[1.7, 3.3, 1.7]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_16.geometry}
//         material={materials['Material.008']}
//         position={[0, 0.3, 0]}
//         scale={[0.7, 1.4, 0.7]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_18.geometry}
//         material={materials['Material.009']}
//         position={[0, 1.8, -0.1]}
//         rotation={[0.7, 0, 0.2]}
//         scale={[2.8, 5.4, 2.8]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_20.geometry}
//         material={materials['Material.008']}
//         position={[0, 0.3, 0]}
//         scale={[0.5, 1, 0.5]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/models/anime_vfx.glb')
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LoganRolphh (https://sketchfab.com/LoganRolphh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/uss-enterprise-star-trek-the-motion-picture-6dcd0dc0030a4d829cffb38903000793
Title: USS Enterprise | Star Trek: The Motion Picture
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Enterprise(props) {
  const { nodes, materials } = useGLTF('/models/uss_enterprise__star_trek_the_motion_picture.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials['mat_16.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['mat_17.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['mat_4.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['mat_8.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['mat_9.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/uss_enterprise__star_trek_the_motion_picture.glb')